"""Core data models: GoalFrame, VerificationResult, Episode."""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import uuid4

from PIL import Image
from pydantic import BaseModel, Field


class GoalFrame(BaseModel):
    """Synthesised image of a desired intermediate robot state, with reasoning trace."""

    model_config = {"arbitrary_types_allowed": True}

    step: int
    description: str
    key_visual_features: list[str]
    reasoning: str  # LLM CoT trace - always preserved
    image: Image.Image
    is_variant: bool = False  # True if generated by ExplorerAgent


class VerificationResult(BaseModel):
    """VLM-based comparison result: actual observation vs intended goal frame."""

    model_config = {"arbitrary_types_allowed": True}

    goal_frame: GoalFrame
    actual_image: Image.Image
    semantic_score: float
    pose_score: float
    contact_score: float
    composite_score: float
    decision: Literal["advance", "retry", "replan"]
    reasoning: str
    retry_count: int


class Episode(BaseModel):
    """One full run from initial state to task success or failure."""

    model_config = {"arbitrary_types_allowed": True}

    id: str = Field(default_factory=lambda: str(uuid4()))
    task_description: str
    initial_image: Image.Image
    goal_frames: list[GoalFrame] = Field(default_factory=list)
    verifications: list[VerificationResult] = Field(default_factory=list)
    success: bool | None = None  # None = in progress
    replan_count: int = 0
    termination_reason: str | None = None
    total_attempts: int = 0
    planning_rounds: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)
